version: "3"

networks:
  invoiceplane:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/17

volumes:
  invoiceplane-db:
    driver: "local"
  nginx_logs:
    driver: "local"
  invoiceplane-app:
    driver: "local"

services:
  php:
    container_name: "invoiceplane-php"
    image: linkopus/invoiceplane-php:latest  # Utilise l'image Docker Hub
    expose:
      - "9000"
    dns:
      - 8.8.8.8
    depends_on:
      - db
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.11
    volumes:
      - invoiceplane-app:/var/www/projects/invoiceplane  # Volume Docker
      - ./resources/docker/php-fpm/php-dev.ini:/usr/local/etc/php/php.ini

  nginx:
    container_name: "invoiceplane-nginx"
    image: linkopus/invoiceplane-nginx:latest  # Utilise l'image Docker Hub
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
    depends_on:
      - php
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.12
    volumes:
      - invoiceplane-app:/var/www/projects/invoiceplane  # Volume Docker
      - nginx_logs:/var/log/nginx
      - ./resources/docker/nginx/invoiceplane.conf:/etc/nginx/conf.d/invoiceplane.conf:ro
      - ./resources/docker/nginx/sites-available:/etc/nginx/sites-available:ro

  db:
    container_name: "invoiceplane-db"
    image: linkopus/invoiceplane-db:latest  # Utilise l'image Docker Hub
    environment:
      - MARIADB_ROOT_PASSWORD=ipdevdb
      - MARIADB_USER=ipdevdb
      - MARIADB_PASSWORD=ipdevdb
      - MARIADB_DATABASE=invoiceplane_db
    ports:
      - "3306:3306"
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.13
    volumes:
      - invoiceplane-db:/var/lib/mysql

  phpmyadmin:
    container_name: "invoiceplane-dbadmin"
    image: phpmyadmin/phpmyadmin:latest  # Utilise l'image officielle PHPMyAdmin de Docker Hub
    environment:
      - PMA_HOST=invoiceplane-db
      - MYSQL_DATABASE=invoiceplane_db
      - MYSQL_USER=ipdevdb
      - MYSQL_PASSWORD=ipdevdb
      - MYSQL_ROOT_PASSWORD=ipdevdb
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=2G
    depends_on:
      - db
    links:
      - db
    restart: always
    volumes:
      - ./resources/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./resources/docker/databases:/var/www/html/tmp/upload_databases
    ports:
      - "8081:80"
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.16
