name: Deploy to Development Environment

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: linkopus/invoiceplane:latest

      - name: Deploy to Dev Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            # Naviguer dans le répertoire du projet
            cd /home/mohammed/InvoicePlane
            if [ -d ".git" ]; then
              git reset --hard
              git clean -fd
              git fetch origin
              git checkout development
              git pull origin development
            else
              echo "Error: /home/mohammed/InvoicePlane is not a git repository."
              exit 1
            fi

            # Utiliser Docker Compose pour recréer les conteneurs
            docker-compose down
            docker-compose up -d

            docker logout
