- name: Deploy to Dev Environment
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.DEV_HOST }}
    username: ${{ secrets.DEV_USER }}
    password: ${{ secrets.DEV_PASSWORD }}
    script: |
      echo "Logging in to Docker Hub"
      echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      docker pull linkopus/invoiceplane:latest
      echo "Stopping and removing existing container if exists"
      if [ "$(docker ps -aq -f name=invoiceplane)" ]; then
        docker stop invoiceplane
        docker rm invoiceplane
      fi
      echo "Running new container"
      docker run -d --name invoiceplane \
        -p ${{ secrets.NGINX_HTTPS_PORT }}:${{ secrets.NGINX_HTTPS_PORT }} \
        -p ${{ secrets.NGINX_HTTP_PORT }}:${{ secrets.NGINX_HTTP_PORT }} \
        -v /home/mohammed/InvoicePlane:/var/www/html \
        linkopus/invoiceplane:latest
      docker logout
      echo "Checking if the directory exists"
      if [ -d "/home/mohammed/InvoicePlane" ]; then
        cd /home/mohammed/InvoicePlane
        if [ -d ".git" ]; then
          git reset --hard
          git clean -fd
          git fetch origin
          git checkout development
          git pull origin development
        else
          echo "Error: /home/mohammed/InvoicePlane is not a git repository."
          exit 1
        fi
      else
        echo "Error: /home/mohammed/InvoicePlane does not exist."
        exit 1
